### PR TITLE
Fixed nested resources keys escaping

### LINKED ISSUE #234: Doesn't escape key within nested resource request.
I use сyrillic symbols at resource key, and for example i have two models `Author` and `Post`.
And when i call
```ruby
Post.where(author_id: 'ЙЦУКЕН123').all
``` 
It raises:
```
authors/ЙЦУКЕН123/posts # bad uri
```

### PR DESCRIPTION
**Pull request by qelphybox**
Fixes #234 . Added basic vagrant provision.

### CODE REVIEW

File: lib/json_api_client/associations/belongs_to.rb [hunk 1]
```diff
@@ -11,14 +11,20 @@ def belongs_to(attr_name, options = {})
...
         def param
           :"#{attr_name}_id"
         end
 
         def to_prefix_path
           "#{attr_name.to_s.pluralize}/%{#{param}}"
         end
+
+        def set_prefix_path(attrs)
+          attrs.merge!(param => encode_part(attrs[param])) if attrs.key?(param)
```
Comment (chingor13) [inline lib/json_api_client/associations/belongs_to.rb]: This will modify the input hash which *could* have issues in the future. It looks like it's currently receiving a copy (modified) from some other input, but we should rebind `attrs = attrs.merge(...) if ...`

Alternatively, if we want to keep modifying the hash, just set the value rather than merging in another hash of one item: `attrs[param] = encode_part(attrs[param]) if attrs.key?(param)`

File: README.md [hunk 2]
```diff
@@ -487,6 +487,16 @@ end
 
 ```
 
+### Development
+
+You can get development environment. It requires [vagrant](https://www.vagrantup.com/).
```
Comment (chingor13) [inline README.md]: This gem doesn't require vagrant for development. Can you remove the vagrant stuff from the PR?

Comment (qelphybox) [inline README.md]: I thought it can be convenient, cause not every developer has ruby environment on his own machine. e.g. for running tests in my case. Are you sure that it must be removed?

Comment (chingor13) [inline README.md]: Yes, please remove it. Rails core development uses vagrant for development because there are many dependencies that are tested against (multiple db versions and such). All this gem requires is ruby 2.2+ and ActiveSupport 3.2+. If someone cannot set that up, then they can set up vagrant or some other vm themselves and shouldn't need this codebase to do it for them.

**Comment by qelphybox** [comment]
@chingor13 Thank you for response. All done.
